### ISSUE TITLE
update NAM geodata

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#57] opened 2018-05-31 12:09 UTC
Some new villages need to be added

**Comment by sbabur** [comment] 2018-07-24 10:30
@onlyjsmith Updated Namibia geodata is attached - let me know if the wizard is up and I can try testing the uploader there


[NAM_vlgs_targeted_2018 (1).zip](https://github.com/disarm-platform/user-requests-and-feedback/files/2223191/NAM_vlgs_targeted_2018.1.zip)

**Comment by onlyjsmith** [comment] 2018-07-24 11:23
Thanks @sbabur! The config editor (wizard) is not deployed publicly yet. So we’ll take a look at the file, and see if we can run it through the automated tests the editor is built on. Will report back inside this issue...

**Comment by onlyjsmith** [comment] 2018-07-26 08:58
@sbabur there are some villages with duplicate names. This will may make it impossible to select in the dropdowns for Monitor and Record (if the villages with duplicate names are in the same constituency). Do you mind, or do you want to change the village names?

**Comment by sbabur** [comment] 2018-07-26 09:02
Ahhhh ok let me take a quick look and check with New Katelyn

**Comment by sbabur** [comment] 2018-07-31 08:53
@onlyjsmith @TNgidi @Nicolaidavies 

The approach we want to go with is to combine the duplicate villages.

Let’s say we have:
Village A, target 50 structures, polygon ABC
Village A, target 50 structures, polygon XYZ

Can we maintain the 2 polygons but have a single Village A with 100 target structures from the perspective of the form location select/dashboard calcukations, or would the polygons also need to be merged somehow?

Sameen

**Comment by Nicolaidavies** [comment] 2018-08-03 07:50
@sbabur 

Currently each polygon shows up as one option in the dropdown. Therefore both polygons would show in the dropdown with this approach.  

We could rename one of the polygons to something that would stop users from selecting it. But this is not ideal.

Will look into this with @onlyjsmith.

**Comment by sbabur** [comment] 2018-08-03 08:07
@Nicolaidavies Thanks for confirming Nicolai - working something out with Dominic, but we will get you a shapefile with 1 polygon, 1 name - I think we will try and just merge the multiple polygons. 

If that doesn't work - honestly, your suggestion about names like ZZZ seems like the better nuclear option from a data collector-not-being-confused perspective

**Comment by sbabur** [comment] 2018-08-03 12:08
@Nicolaidavies  See attached final geodata plan as a multipolygon

[nam_vlg_2018_multi_targeted.zip](https://github.com/disarm-platform/user-requests-and-feedback/files/2257262/nam_vlg_2018_multi_targeted.zip)

**Comment by Nicolaidavies** [comment] 2018-08-06 13:19
The NAM villages have been updated and deployed to staging and production.

**Comment by Nicolaidavies** [comment] 2018-08-06 13:42
We are looking into extracting risk onto the villages.

**Comment by onlyjsmith** [comment] 2018-08-06 14:11
As @Nicolaidavies mentioned, we're extracting risk back onto the geodata. At the moment it works fine at the moment, but the areas show up black on the dashboard map. Will update this card when we've updated the geodata.

**Comment by HughSt** [comment] 2018-08-29 21:00
Looks like I did this on August 6th - seem to remember putting the file back into the thread here on GitHub but that must have been a different issue..attaching again
[nam.villages.geojson.zip](https://github.com/disarm-platform/user-requests-and-feedback/files/2333768/nam.villages.geojson.zip)

**Comment by Nicolaidavies** [comment] 2018-08-30 11:28
@sbabur I've updated the villages on nam staging. Could you give it a test? 

Will move to production when you give the the go-ahead.

**Comment by TNgidi** [comment] 2018-09-04 08:34
In an email @sbabur  confirmed this ready to close

**Closed as completed** 2018-09-14 12:30 UTC
Labels: question, [tool] IRS, data
