### ISSUE TITLE
BWA + NAM manually ensure given geodata polygon IDs are unique

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#41] opened 2018-05-17 12:33 UTC

**Comment by onlyjsmith** [comment] 2018-05-17 15:02
@sbabur referring to a similar issue from last year (https://gitlab.com/disarm/douma-app/issues/398), I've updated the villages geodata the same way.

In addition, there were 4 villages without names (in the `VILLAGE` field). They were `Id` 2, 
3, 4 and 5. I've added them as `VILLAGE_ID_2`, `VILLAGE_ID_3`, `VILLAGE_ID_4`, and `VILLAGE_ID_5`.

I'm attached a ZIP with the current village and district geodata which is live on both production and staging.

Please note, that for the time being, if the geodata is updated, you need to visit the `/meta/geodata` page and redownload them manually. We're working on making this more automatic, but as these files can be quite large, we don't force the user to get them every time they connect.

[BWA village and district geodata - staging and production - May 17, 2018 17:01.zip](https://github.com/disarm-platform/user-requests-and-feedback/files/2013693/BWA.village.and.district.geodata.-.staging.and.production.-.May.17.2018.17.01.zip)

**Comment by onlyjsmith** [comment] 2018-05-18 03:49
@sbabur Confirming that you don’t need to visit `/meta/geodata`, it tells you there’s updated geodata.

Linked issue of #43, would reduce required data downloads.

**Comment by sbabur** [comment] 2018-05-20 13:58
@onlyjsmith Working on this with Katelyn - will provide you with the updated file containing re-assigned unique ID's + village names shortly.

**Comment by sbabur** [comment] 2018-05-21 11:38
@onlyjsmith from Katelyn, we can provide you with these fixes + the HOT updates all bundled together in ~3 weeks? That way you only need to make 1 swap. Does that work? 

"I can make these changes and ensure the IDs from last year are the same, but is this needed urgently? We are hoping to make updates to the shapefile over the next three weeks during the HOT-Phase II trainings. 

I will also add names to those missing during this time period. "

**Comment by onlyjsmith** [comment] 2018-05-23 12:03
That sounds good. We’re working on some better ways to validate new geodata, which we hope will be functional by then.

**Comment by onlyjsmith** [comment] 2018-05-23 12:09
We’ve noted duplicate villages with an `Id` field of: 38, 377 
We’ve noted MultiPolygon villages with an `Id` field of: 349

**Comment by sbabur** [comment] 2018-05-29 15:52
@onlyjsmith Thanks - can we move this to 'Waiting or Blocked'? so it stays on our to-do list?

**Comment by TNgidi** [comment] 2018-05-30 07:21
Moved

**Comment by sbabur** [comment] 2018-05-30 10:22
Note to self: Xaixai needs to be in Okavango, not Ngami

**Comment by sbabur** [comment] 2018-08-15 04:45
@onlyjsmith @TNgidi @Nicolaidavies 

We have the updated geodata for Botswana to include all districts. There is a unique ID column and an ID column. The ID one has a few duplicates, but the unique ID one does not. Can you remind me where the underlying issue was with these IDs?

If all is good to go with this shapefile, please swap the geodata. Otherwise, let me know if changes need to be made. 

Apologies for the delay on this - required a lot of district engagement. Trainings are on Aug 27th so hoping we can have this done by EOW latest. 

[BotswanaIRSvillages_2018.zip](https://github.com/disarm-platform/user-requests-and-feedback/files/2289221/BotswanaIRSvillages_2018.zip)

**Comment by sbabur** [comment] 2018-08-15 04:47
@onlyjsmith @TNgidi @Nicolaidavies 

It looks like you added the unique ID column and started using that? If so, great - Dominic stuck with ensuring that column was unique.

**Comment by TNgidi** [comment] 2018-08-16 06:59
@sbabur thank you sending the file, we will validate it and upload it to staging version if valid. We will test it then let you know to test too.

**Comment by Nicolaidavies** [comment] 2018-08-16 07:49
@sbabur 

We will use the `unique_ID` as the id field, because all values are unique. There are still some duplicates for the field `Id`.

We've used the field `VILLAGE` as the display field (what the user sees), but it's not unique. This means duplicates will show up in the location_selection and ultimately affect the aggregations on the dashboard. 

Can you make `VILLAGES` unique?

**Comment by sbabur** [comment] 2018-08-16 08:03
@Nicolaidavies I think we are ok with the duplicate villages given that we show district alongside it, so users will know which one is which. 

![image](https://user-images.githubusercontent.com/37877007/44196227-a220c880-a13b-11e8-8211-c7590c2f9a73.png)

**Comment by Nicolaidavies** [comment] 2018-08-16 08:04
@sbabur 

Ok, I will update the geodata on staging and let you know when it's ready for testing.

**Comment by sbabur** [comment] 2018-08-16 08:04
@Nicolaidavies One thing I did notice though - can you make the case consistent? I see there is a mix of Village and VILLAGE

I can ask Dominic as well but not sure he will respond quickly

**Comment by Nicolaidavies** [comment] 2018-08-16 08:07
@sbabur 

I would prefer if Dominic can do it, that way the source file gets fixed. Then we can avoid updating it when/if changes need to be made. 

Since it's a cosmetic thing, I will still go ahead and test it on staging.

**Comment by sbabur** [comment] 2018-08-16 08:14
@Nicolaidavies No problem - will reach out to Dominic

**Comment by Nicolaidavies** [comment] 2018-08-16 08:16
@sbabur Thank you. 

I've updated the villages on staging. The config version is 1.0.23.

@TNgidi is currently testing it. 

I will push to production when you, @sbabur, say go.

**Comment by sbabur** [comment] 2018-08-16 08:18
@Nicolaidavies Thanks! I'll be occupied training Namibia on DiSARM for the rest of the day but will test out this evening.

**Comment by sbabur** [comment] 2018-08-20 06:07
@Nicolaidavies @TNgidi Here is the final shapefile Nicolai. I checked out the previous version on Staging and it looked good, but I can go ahead and test this new one on Staging too before its committed to production. Dominic fixed the text case and added in the missing risk values. We do have a lot of missing structure counts and room counts (for non-targeted) villages due to getting this information directly from the districts, but this will suffice for the upcoming campaign since we have targeted structures for every target village that will be in the plan

[BotswanaIRSvillages_2018_final.zip](https://github.com/disarm-platform/user-requests-and-feedback/files/2301285/BotswanaIRSvillages_2018_final.zip)

**Comment by sbabur** [comment] 2018-08-22 07:22
@Nicolaidavies @mosaic141688 Checking in on the shapefile swap. As a heads up, Botswana trainings start on Monday the 27th so want to make sure this is validated and ready to go in advance.

**Comment by HughSt** [comment] 2018-08-22 20:23
@sbabur - just acknowledging your message. Nicolai has been out sick but will get to this on his return.

**Comment by sbabur** [comment] 2018-08-23 06:42
@HughSt Hi Hugh - noted. Can we plan for some potential troubleshooting availability over the weekend then? We are doing practicals with the entire Botswana team starting Monday so we need to ensure there is enough time for me to test and report any potential problems. I don't envision any given the Botswana shapefile update has been straightforward thus far, but should plan accordingly just in case.

**Comment by Nicolaidavies** [comment] 2018-08-23 06:57
@sbabur Thank you for your patience. 

I've updated the villages on staging. 

I can update production when you give the go-ahead.

**Comment by sbabur** [comment] 2018-08-23 07:55
@Nicolaidavies Thanks Nicolai, looks good, - you can move to production and I'll do end-to-end testing tonight in the slim chance there is any issue that pops up. 

Hope you are feeling better!

**Comment by Nicolaidavies** [comment] 2018-08-23 08:01
@sbabur 

The villages are now updated on production. 

Thanks, I'm getting there slowly.

**Comment by TNgidi** [comment] 2018-09-04 08:37
@sbabur confirmed that we can close this in an email

**Closed as completed** 2018-09-14 12:30 UTC
Labels: bug, [tool] IRS, data
