### ISSUE TITLE
cleanup Namibia plan

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#58] opened 2018-05-31 12:09 UTC
Combine smaller plans

**Comment by sbabur** [comment] 2018-07-24 10:35
@onlyjsmith Removing blockers!

Can you please:
1. Delete all plans except for the oldest one highlighted below (with 2085 targets)
2. If straightforward, create a single '2018 IRS Plan' with all the villages in the attached geodata file (this is the same as the base geodata - we are just loading in geodata for targeted villages at the moment) - if not I will just have to manually select each constituency and then draw a big polygon to select every last village for their plan

![image](https://user-images.githubusercontent.com/37877007/43133096-ff7db016-8f3d-11e8-9390-78f2a53a1818.png)

[NAM_vlgs_targeted_2018 (1).zip](https://github.com/disarm-platform/user-requests-and-feedback/files/2223213/NAM_vlgs_targeted_2018.1.zip)

**Comment by onlyjsmith** [comment] 2018-07-24 11:26
@sbabur

1. Can delete the plans as described - will leave a single 2017 plan with 2085 targets.
2. For 2018 plan, are you saying to create a single plan using all the villages? (i.e. this is the same file as attached to #57 for updating the NAM geodata)

**Comment by sbabur** [comment] 2018-07-24 12:19
2 – yes that is correct

**Comment by onlyjsmith** [comment] 2018-07-26 11:34
@sbabur Done on production.

**Comment by onlyjsmith** [comment] 2018-07-26 11:51
@sbabur Correction - almost done! Waiting for updated geodata. We have a skeleton for the new combined plan ready to go.

**Comment by Nicolaidavies** [comment] 2018-08-06 13:31
@sbabur 

We updated the plan on production. It's called "2018 IRS Plan" with 2138 areas.

**Comment by sbabur** [comment] 2018-08-07 07:08
@onlyjsmith @Nicolaidavies I'm looking at the plan, and the 2138 part looks correct, but only a lot of villages don't look selected - is this because of multipolygons? I didn't think there were that many. 

![image](https://user-images.githubusercontent.com/37877007/43760102-71705dd4-9a21-11e8-96b0-1615f13d7e65.png)

**Comment by onlyjsmith** [comment] 2018-08-07 09:28
@sbabur Thanks - we'll take a look before the call later.

**Comment by Nicolaidavies** [comment] 2018-08-07 10:46
@sbabur could I get you to test it in incognito? 

We've discovered a bug related to updating the geodata, that's probably what's causing the plan to not show up correctly.

**Comment by TNgidi** [comment] 2018-09-04 08:39
We can close this one, as @sbabur  confirmed in an email

**Closed as completed** 2018-09-14 12:31 UTC
Labels: [tool] IRS, data
