### ISSUE TITLE
Records created yesterday on test instances not appearing

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#46] opened 2018-05-18 10:11 UTC
I created and synced 1 record each for the following Namibia test instances. I'm not seeing them in Monitor even after selecting 'Include responses outside of plan' 

Instance   ID
vayoxodo-436     
tilipimi-8
wixocaye-904
tujiwupo-868
hudiyipu-307 
locesavi-476
yuzenogo-271
nocapiyo-144

**Comment by onlyjsmith** [comment] 2018-05-21 14:24
@sbabur We can't find any records in _app-stage_ DB, and we can't reproduce. I can find records in the live production DB matching those instance_ids. Is it possible you're saving in e.g. `nam.app-stage`, and trying to load again in `nam.app`?

**Comment by sbabur** [comment] 2018-05-22 06:31
@onlyjsmith I was recording these record in nam.app using the listed test instances. Do you see any records there from May 17th? Its always possible I saved in nam.app-stage but I really don't think this was the case.

**Comment by onlyjsmith** [comment] 2018-05-22 07:03
Thanks for confirming - I misunderstood the ‘test’ instances in the original post. We can see the records in the DB on `nam.app`, but I also cannot get them to reappear on the Monitor page. Will investigate further.

**Comment by sbabur** [comment] 2018-05-22 07:04
@onlyjsmith Thanks! Phew - glad you are able to see them and you have the breadcrumbs you need.

**Comment by onlyjsmith** [comment] 2018-05-25 10:42
We were not able to reproduce this issue. We can see the records on Monitor. It’s possible that an instance without a plan was causing problems, but we might have fixed whatever issue was causing is, as we can’t reproduce that use-case either.

**Comment by onlyjsmith** [comment] 2018-05-25 10:43
@sbabur Can you confirm if it still happens? Maybe we can close and reopen if it reopens.

**Comment by sbabur** [comment] 2018-05-25 11:44
@onlyjsmith On version 1.2.2 hudiyipu-307

I've selected:
Season - March 2018
Plan - IRS 2017 Plan with 20 villages
Advanced - show responses outside plan area

I still don't see the record from May 17th. Is there something am I missing here, as you mentioned you see it in the db?

Also, with the 20-village plan loaded, I still see ALL villages in the map. Related to Issue #42 

![screencapture-nam-app-disarm-io-irs-monitor-2018-05-25-13_39_25](https://user-images.githubusercontent.com/37877007/40542721-a7afd490-6021-11e8-931f-45769ad41dc9.png)

**Comment by onlyjsmith** [comment] 2018-05-25 11:55
Thanks - will re-investigate.

**Comment by onlyjsmith** [comment] 2018-05-25 12:40
Right. I was finally able to reproduce! If you visit reset on  `/reset.html` , then it should go away. Could you confirm on one of the instances? In the meantime, we’re implementing a fix. 

The good news is that it _should_ only affect someone testing a bunch of different intances - basically it remembered the last response you retrieved from the network and tells the server “give me everything after this”. Somehow that value is not clearing when you change instances (although we do a careful clear of state data when you login).

**Comment by onlyjsmith** [comment] 2018-05-25 14:16
Fixed on v1.2.3, deployed to production. Confirm I can see the 1 record on `hudiyipu-307` instance.

**Comment by sbabur** [comment] 2018-05-25 14:55
@onlyjsmith Great, its working for me!

**Comment by sbabur** [comment] 2018-05-25 14:58
@onlyjsmith Can close this and #42

**Closed as completed** 2018-05-27 07:48 UTC
Labels: bug, [tool] IRS, data
